name: 'Setup gcloud environment'
description: 'Setup a gcloud environment and add it to the PATH'
author: 'GoogleCloudPlatform'
inputs:
  version:
    description: 'The version of the gcloud SDK to be installed.  Example: 278.0.0'
    default: 'latest'
    required: false
  service_account_email:
    description: 'The service account email which will be used for authentication.'
    required: false
  service_account_key:
    description: 'The service account key which will be used for authentication.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
